---
apiVersion: v1
kind: Service
metadata:
  name: privatepages-api
spec:
  type: ClusterIP
  selector:
    app: privatepages-api
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: privatepages-api
spec:
  selector:
    matchLabels:
      app: privatepages-api
  template:
    metadata:
      labels:
        app: privatepages-api
    spec:
      volumes:
        - name: config
          configMap:
            name: privatepages
        - name: data
          persistentVolumeClaim:
            claimName: privatepages-data
      containers:
        - name: nginx
          image: "nginx:1.23"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: data
              mountPath: /var/www/html
        - name: app
          image: privatepages-api
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: privatepages
              containerPort: 8080
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: info
            - name: HTTP_LISTEN
              value: ":8080"
            - name: HTTP_UPLOAD_MAX_SIZE
              value: "100"
            - name: ARTIFACT_STORAGE_PATH
              value: "/data"
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: privatepages-api
                  key: API_SECRET

# ---
# apiVersion: monitoring.coreos.com/v1
# kind: PodMonitor
# metadata:
#   name: privatepages-api
#   labels:
#     release: prometheus # release name of prom-stack chart
# spec:
#   selector:
#     matchLabels:
#       app: privatepages-api
#   podMetricsEndpoints:
#     - port: main
#       interval: 30s
#       path: /metrics
#       targetPort: 80
