---
apiVersion: v1
kind: ConfigMap
metadata:
  name: privatepages
data:
  default.conf: | 
    server {
        listen              80;
        server_name         _;

        location ~ /(upload|remove)$ {
            client_max_body_size 1024M;
            proxy_pass       http://127.0.0.1:8080;
            proxy_set_header Host             $host;
            proxy_set_header X-Real-IP        $remote_addr;
            proxy_set_header X-Scheme         $scheme;
        }

        location / {
            root /var/www/html;
            autoindex on;
            index index.html;
        }
    }
